Service/adds hastebin
VivumLab/VivumLab pull request #145
Opened 2020-11-04 00:00 UTC by denis-ev

#119 adds hastebin

2020-11-04 01:26 UTC, voryzen submitted a review, later dismissed

2020-11-04 01:26 UTC, voryzen commented on roles/vivumlab_config/templates/config.yml
> +  devices: !!str '{{ octoprint.devices | default([]) }}'
Was this supposed to be there?

2020-11-04 01:26 UTC, voryzen commented on tasks/AddPackageTasks.sh
> + Task::add_package() {
Shouldn't this be in its own PR?

2020-11-04 21:40 UTC, denis-ev commented on tasks/AddPackageTasks.sh
> + Task::add_package() {
Good catch, yes it should be.

2020-11-04 21:51 UTC, denis-ev commented on roles/vivumlab_config/templates/config.yml
> +  devices: !!str '{{ octoprint.devices | default([]) }}'
Well this threw an error, so I had to include it.

2020-11-05 22:53 UTC, voryzen commented on roles/vivumlab_config/templates/config.yml
> +  devices: !!str '{{ octoprint.devices | default([]) }}'
I figured this should be in its own PR, so the error is documentated.

But we are also cleaning up the changelog, so I'm not sure what the go is

2020-11-05 23:01 UTC, denis-ev commented on roles/vivumlab_config/templates/config.yml
> +  devices: !!str '{{ octoprint.devices | default([]) }}'
This is outdated and not even accurate any more. haha. 
It's not in this PR!

2020-11-25 01:56 UTC, voryzen approved these changes

2020-11-25 01:57 UTC, voryzen commented on group_vars/all
> ----
Waiting on your reply, @denis-ev

2020-11-25 01:58 UTC, voryzen commented on tasks/AddPackageTasks.sh
> -  # Edit the config tempfile
Waiting on your reply, @denis-ev

2020-11-25 01:59 UTC, voryzen requested changes
Waiting on your resolutions, @denis-ev

2020-11-30 22:24 UTC, denis-ev commented on group_vars/all
> ----
yes, those dashes are not supposed to be there.

2020-12-01 02:21 UTC, voryzen approved these changes

2020-12-01 11:57 UTC, merged