refactor(traefik): not explosing open ports unless required
VivumLab/VivumLab pull request #167
Opened 2020-11-25 01:36 UTC by voryzen

For now, the typical use case.. deploying own the users own infrastructure, not using bastion, and not deploying mailu; the fix detailed below should work.

Fixes:
- Unless bastion is enabled, port 2222 is not used.
- Unless healthchecks is enabled, port 25 in not used.

To consider, after merging:
- gitea ssh port should be changed from 2222 (will clash with bastion)
- vagrant 'ansible port' should be changed from 2222
- bastion will also require 25 (wireguard's keepalive port)
- if healthchecks or bastion enable option is changed, after deploying; Vivum will need to restart traefik, after redeploying

2020-11-30 00:46 UTC, voryzen commented
@codefriar @denis-ev could you weigh in here, please.

I have been in contact with a user, and they are concerned about security, in relation to the dashboard ports.

With this new fix, traefik will not open port 8081 and 8082, if expose_internally or expose_externally are not set.

I'm happy with this so far; however, I do have a question, where do you both land on adding basic auth and a userfile to the traefik container?

2020-12-01 01:00 UTC, denis-ev commented on roles/vivumlab_deploy/templates/traefik.yaml
> +{% endif %}
You sure Bastion needs this port?
I think only Gitea needs this and we could possibly set this via a variable in the config.

2020-12-01 01:00 UTC, denis-ev requested changes

2020-12-01 01:00 UTC, denis-ev commented on roles/vivumlab_deploy/templates/traefik.yaml
> +{% endif %}
We can get rid of this for now, until healthchecks incoming mails work, because they don't work yet.

2020-12-01 02:16 UTC, voryzen commented on roles/vivumlab_deploy/templates/traefik.yaml
> +{% endif %}
Its under the bastion heading in the config file..

If bastion doesn't need it, then why is it there?

2020-12-01 02:16 UTC, voryzen commented on roles/vivumlab_deploy/templates/traefik.yaml
> +{% endif %}
Can we leave it, so its available when we get health checks working?

2020-12-01 04:04 UTC, denis-ev commented on roles/vivumlab_deploy/templates/traefik.yaml
> +{% endif %}
```suggestion
# {% if healthchecks.enable %}
#  smtp:
#    address: :25
# {% endif %}
```

2020-12-01 04:42 UTC, voryzen commented
Ports 2222 and 25 commented out.

Lets merge now

2020-12-01 04:46 UTC, denis-ev commented on roles/vivumlab_deploy/templates/traefik.yaml
> +#{% endif %}
```suggestion
# {% if bastion.enable %}
#  ssh:
#    address: ":2222"
# {% endif %}
```

2020-12-01 05:00 UTC, denis-ev approved these changes
Added variables ping and metrics in config/vault.yml
Default (false)

2020-12-01 07:48 UTC, merged