fix(services): correct ownership permissions
VivumLab/VivumLab pull request #230
Opened 2020-12-21 16:09 UTC by voryzen

closes #224

2020-12-22 03:56 UTC, voryzen commented
@VivumLab/core-team team, this is pretty much done; just needs a check over
@denis-ev could you please review the docs main.yml; I'm not sure it's entirely correct

2020-12-23 12:57 UTC, denis-ev commented on roles/turtl/tasks/main.yml
>    become: yes
Why? This defeats the whole purpose of the step before? The folder should be owned by the user and not by root.
This makes the folder to be owned by root!

2020-12-23 12:59 UTC, denis-ev commented on roles/pixelfed/tasks/main.yml
>      path: "{{ volumes_root }}/pixelfed/{{ item }}"
one of the items is not gonna be created right (db), because the item is called pixelfed/db.

2020-12-23 13:01 UTC, denis-ev commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> +      - traefik_network
Why is App in the Traefik_network, it exposed nothing towards Traefik?

2020-12-23 13:02 UTC, denis-ev commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> -      - hubzilla_frontnet
Here is the hubzilla_internal network missing.

2020-12-23 13:04 UTC, denis-ev commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> +      - hubzilla_internal
How is cron connected to Hubzilla? 
Shouldn't there be volumes?

2020-12-23 13:11 UTC, voryzen commented on roles/pixelfed/tasks/main.yml
>      path: "{{ volumes_root }}/pixelfed/{{ item }}"
good catch..
I've got stop using the touchpad on my laptop

2020-12-23 13:15 UTC, voryzen commented on roles/turtl/tasks/main.yml
>    become: yes
the db needs to created with the postgres user... which defaults to... 70, i think.

postgres does this itself, we use ansible here, just to make sure it's available for postgres to use

2020-12-23 13:18 UTC, voryzen commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> +      - traefik_network
good question.. you will notice that the web container, is only available to the traefik network, and not the internal network.

this is by design, so that traefik itself has no access to the other docker containers; the app container is only there to have untethered communication to the web container

2020-12-23 13:22 UTC, voryzen commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> -      - hubzilla_frontnet
good point.

I explained on the earlier review, the web container does not need access to the db, nor the cron job, but does require access to the app container (php-fpm)..

2020-12-23 13:23 UTC, voryzen commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> +      - hubzilla_internal
Good catch, it should have a volume

2020-12-23 13:33 UTC, voryzen commented
Another review, please @VivumLab/core-team

2020-12-23 22:35 UTC, denis-ev commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> +      - traefik_network
Then put the app container in the internal and not Traefik ...

2020-12-23 22:39 UTC, denis-ev commented on roles/authelia/tasks/main.yml
>      path: "{{ volumes_root }}/authelia/{{ item }}"
```suggestion
    path: "{{ volumes_root }}/{{ item }}"
```

because your items are called `Authelia/config`

2020-12-24 13:43 UTC, voryzen commented on roles/hubzilla/templates/docker-compose.hubzilla.yml.j2
> +      - traefik_network
It needs both. What's the problem, exactly?

2020-12-24 13:48 UTC, voryzen commented on roles/authelia/tasks/main.yml
>      path: "{{ volumes_root }}/authelia/{{ item }}"
Yea, actually this can be changed.

good catch

2020-12-25 05:41 UTC, voryzen commented
As for as hubzilla goes, it can stay the way it is..

It will need further work, but at least, the basic structure that we want for the docker-compose/main.yml files are now being followed

2020-12-26 10:57 UTC, denis-ev requested changes

2020-12-26 10:57 UTC, denis-ev commented on roles/docs/tasks/main.yml
> +    force: yes
This will not work like this, please undo all changes and leave as is.

2020-12-26 10:57 UTC, denis-ev commented on roles/docs/templates/docker-compose.docs.yml.j2
> -    image: vivumlab/docusaurus:{{ docs.version }}
Why did you change all this?

2020-12-26 11:21 UTC, denis-ev commented on roles/vivumlab_config/templates/config.yml
> -  armv7: "verified"
undo this, this is verified for amd64 and the images for the other two are definitely build

2020-12-26 11:23 UTC, denis-ev commented on roles/vivumlab_deploy/tasks/main.yml
> +  when: query | bool
have you tested this?
I've tried it before and it did not work.
I would recommend to remove those changes and test them with the new cli and change them in that PR

2020-12-26 13:02 UTC, voryzen commented on roles/docs/tasks/main.yml
> +    force: yes
make the necessary changes, or reverts, and I'll accept them

2020-12-26 13:03 UTC, voryzen commented on roles/docs/templates/docker-compose.docs.yml.j2
> -    image: vivumlab/docusaurus:{{ docs.version }}
make the necessary changes, or reverts, and I'll accept them

2020-12-26 13:10 UTC, voryzen commented on roles/docs/templates/docker-compose.docs.yml.j2
> -    image: vivumlab/docusaurus:{{ docs.version }}
I'm looking at the code, and I don't actually remember making that change..

2020-12-26 13:10 UTC, voryzen commented on roles/vivumlab_config/templates/config.yml
> -  armv7: "verified"
I don't remember making this change, either

2020-12-26 13:13 UTC, voryzen commented on roles/vivumlab_deploy/tasks/main.yml
> +  when: query | bool
Nah, I'm not actually sure what it little piece of code does..
I don't think I changed it

2020-12-26 13:29 UTC, denis-ev commented on roles/vivumlab_config/templates/config.yml
> +  amd64: "verified"
```suggestion
  amd64: "verified" {# "verified" or "supported" or "unsupported" or False #}
```

2020-12-26 13:35 UTC, denis-ev commented on roles/vivumlab_config/templates/config.yml
> +  armv7: False
```suggestion
  version: {{ docs.version | default("1.0.4") }}
  amd64: "verified" {# "verified" or "supported" or "unsupported" or False #}
  arm64: "verified"
  armv7: "verified"
```

2020-12-26 13:37 UTC, denis-ev approved these changes

2020-12-26 13:37 UTC, merged

2020-12-30 00:28 UTC, denis-ev commented
:tada: This PR is included in version 0.5.3 :tada:

The release is available on [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.5.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: