feat: cache docker images
VivumLab/VivumLab pull request #277
Opened 2021-01-09 11:46 UTC by denis-ev

2021-01-10 05:28 UTC, codefriar requested changes

2021-01-10 05:28 UTC, codefriar commented on group_vars/all
> -  wireguard:
Why take this out?

2021-01-10 05:28 UTC, codefriar commented on group_vars/all
> -  wireguard:
Nvme mind

2021-01-10 05:28 UTC, codefriar commented on roles/vivumlab_config/templates/config.yml
> -    2222: 22
These ports should remain. They're needed for smtp and ssh

2021-01-10 06:54 UTC, denis-ev commented on roles/vivumlab_config/templates/config.yml
> -    2222: 22
I made the port 2222 a custom port, which would be the same as the variable vlab_port.
And I removed the others for security, they would be forwarded from a public accessible server to your own and maybe when the certain services are not running, not even used.
If you want any port, we can add them with an if so they would only be there if needed. 
And with the for loop underneath, everything you have already in there will stay there, if you added stuff before, that would just be gone, now it's saved and not overwritten.

2021-01-10 22:58 UTC, codefriar commented on roles/vivumlab_config/templates/config.yml
> -    2222: 22
Gotcha. Will test tonight.

2021-01-11 20:21 UTC, codefriar commented
@denis-ev  - give these changes a test please.

2021-01-11 22:16 UTC, codefriar commented
@denis-ev  - I feel some urgency on this one, as right now vlab update will nuke any existing bastion server in a way that is not easily recoverable without an out of band console access to the machine - it literally will cause a nat/snat/dnat redirection of port 22 to port 22 which... effectively blocks all incoming port 22 traffic

2021-01-12 16:24 UTC, denis-ev commented
@codefriar this one should be good to go, if you could test it again?

2021-01-12 17:44 UTC, codefriar approved these changes

2021-01-12 17:44 UTC, merged