fix: Gitea options
VivumLab/VivumLab pull request #418
Opened 2021-05-31 16:23 UTC by joao-p-marques

- Update volumes mapping (everything is now stored in /data)
- Unify SSH configuration. SSH_PORT is the one that is shown in the URL for cloning (See https://docs.gitea.io/en-us/config-cheat-sheet/#server-server) but we can use always the same port inside and outside of the container to avoid issues
- Don't use docker's user option, but use instead the built-in Gitea one

2021-06-05 01:59 UTC, denis-ev requested changes

2021-06-05 01:59 UTC, denis-ev commented on roles/gitea/templates/docker-compose.gitea.yml.j2
> -      - "{{ volumes_root }}/gitea/data:/var/lib/gitea"
I don't think you should change this.
I just went into my Gitea container ...

```
vlab@vlab:/var/vivumlab/gitea$ docker-compose exec gitea /bin/bash
bash-5.1$ ls
addrs=127.0.0.1:6379 db=0  indexers
custom                     queues
data                       ssh
git
bash-5.1$ pwd
/var/lib/gitea
bash-5.1$ cd /data
bash: cd: /data: No such file or directory
```

2021-06-06 14:31 UTC, joao-p-marques commented on roles/gitea/templates/docker-compose.gitea.yml.j2
> -      - "{{ volumes_root }}/gitea/data:/var/lib/gitea"
Mmm ok, what version is your Gitea container running? Taking a look at https://docs.gitea.io/en-us/install-with-docker/#basics you can see that it is recommended to map `/data` to the outside, it seems that it is the current path where Gitea stores info.

2021-06-07 00:45 UTC, denis-ev commented
Well I’m using the rootless image which is not /data and we have as a default too. 

https://docs.gitea.io/en-us/install-with-docker-rootless/

> On 6. Jun 2021, at 22:31, João Marques ***@***.***> wrote:
> 
> ﻿
> @joao-p-marques commented on this pull request.
> 
> In roles/gitea/templates/docker-compose.gitea.yml.j2:
> 
> >      restart: unless-stopped
>      volumes:
> -      - "{{ volumes_root }}/gitea/data:/var/lib/gitea"
> Mmm ok, what version is your Gitea container running? Taking a look at https://docs.gitea.io/en-us/install-with-docker/#basics you can see that it is recommended to map /data to the outside, it seems that it is the current path where Gitea stores info.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2022-01-18 10:50 UTC, merged