refactor(service): fix env values
VivumLab/VivumLab pull request #59
Opened 2020-10-05 12:49 UTC by voryzen

RSSHub had some weird http basic auth values in the environment variables.
even when they were uncommented, they did nothing.

replaced it with a valid variable (TZ)

2020-10-06 00:36 UTC, denis-ev requested changes

2020-10-06 00:36 UTC, denis-ev commented on roles/rsshub/templates/docker-compose.rsshub.yml.j2
> +      - TZ=Etc/UTC
We got a variable for this 

```suggestion
      - TZ={{ common_timezone }}
```

2020-10-06 02:35 UTC, voryzen commented
Forgot about that var.

Good catch

2020-10-06 02:41 UTC, merged

2020-10-07 01:48 UTC, denis-ev commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- `v0.1.0`
- [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-07 02:41 UTC, denis-ev commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- `v0.1.0`
- [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-07 03:05 UTC, denis-ev commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- `v0.1.0`
- [GitHub release](https://github.com/VivumLab/VivumLab/releases/tag/v0.1.0)
- `v0.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: